---
title: "Costing implementation strategies (Cost-IS) instrument"
format: html
include-in-header: Cost-IS_google_analytics.html
---


Cost-IS is an instrument for costing implementation strategies in the digital health setting. 

Cost-IS's aim and scope is to collect data on the costs associated with implementation strategies for digital health innovations. The instrument provides a pragmatic and flexible approach that can be tailored to meet the needs of various projects. 

Reliable implementation cost estimations produced from this standardised tool will inform appropriate resourcing for implementation strategies resulting in a greater likelihood of implementation success. As well as providing decision makers with reliable information from economic evaluations of health care innovations that account for the full extent of costs. It is anticipated that the transdisciplinary nature of Cost-IS will contribute to an expanded knowledge of implementation costs through improved collaboration between implementation scientists and health economists. Further piloting of Cost-IS is required for validation.


Cost-IS comprises of three data collection templates: template 1, 2, and 3.

### Template 1: Planning 

The purpose of template 1 is to help identify specific data items that need to be collected. This will allow for comprehensive and targeted data collection later in the costing instrument. 

A project's implementation strategies are listed under the first column. For each strategy, the activities and resources (labour and non-labour) required to operationalise the strategy are listed under the relevant columns.

### Template 2: Data collection

Template 2 is used to collect the data necessary to quantify the cost of resources associated with the implementation strategies.

The level of detail to include depends on the project. We found that the listed columns in the template provided sufficient granularity for the subsequent analysis. The template is flexible and can be adjusted to meet the needs of your project, by altering the columns and their content. 

### Template 3: Resource valuation

Template 3 enables the valuation of the identified resources. This is a separate template for clarity and ease of update. Template 3 informs Template 2’s columns ‘hourly wage rate’ and ‘resource- category’.

###Cost analysis

Subsequent analysis from the data collected in the completed templates should be conducted in a meaningful way to the project as determined by the analyst. The templates were designed to collect data at varying levels of detail because of the wide range and adaptable nature of implementation projects. 


## Download

[Cost-IS templates](https://github.com/Thomasina-Donovan/implementation-costing-instrument/raw/main/assets/Cost-IS_TemplatesBlank_V3.xlsx)

[Cost-IS user guide](https://github.com/Thomasina-Donovan/implementation-costing-instrument/raw/main/assets/AF_3_Cost-IS_UserGuide_V0.xlsx)



# Worked example of Cost-IS
## Template 1

The worked example of template 1 includes four implementation strategies with associated activities and resources.


## Template 2A: Data collection- labour

In the worked example of template 2A, all activities associated with the hypothetical implementation were recorded. Each activity instance was given a specific index number because an activity occurred more than once. Similarly, a purpose was recorded for each activity to distinguish it from other similar activities. The implementation strategy related to the respective activity was documented in the same row. Personnel involved in the activity are documented. Each personnel type/role was recorded on a separate row, roles were distinguished by wage rate or title classification. For each activity, the number of personnel for each role was recorded. Finally, the time spent on the activity for that role was documented. The two final columns automatically calculate labour costs when the other columns are completed. The entries columns ‘Activity’, ‘Strategy’ and ‘Role’ are restricted by drop down menus containing what was listed in template 1. Template 1 can be completed iteratively as required by the project.


## Template 2B: Data collection- non-labour

The worked example of template 2B  contains two non-labour resources used in the hypothetical implementation. Each resource is listed in the first column as listed in template 1, with its corresponding strategy in the next column.

## Summary tables

The worked example demonstrates how implementation costs can be summarised by role and implementation strategy.

## Download

[Cost-IS templates- worked example](https://github.com/Thomasina-Donovan/implementation-costing-instrument/raw/main/assets/Cost-IS_WorkedExample_V3.xlsx)



# Development of Cost-IS

Cost-IS was developed iteratively across three phases. Phase 1 involved a systematic literature review to identify the nature of implementation costs and the methods used to measure and value these costs, within the context of hospital-based clinical decision support systems initiatives. Phase 2 consisted of qualitative semi-structured interviews that outlined current practices for capturing the costs associated with implementing digital health initiatives in hospital settings. Phase 3 development involved a modified electronic-Delphi (e-Delphi) process to generate a consensus on the core components and design of an implementation costing instrument.

#### Phase 1 findings
A prototype of the implementation costing instrument was first developed from findings from a literature review and qualitative interviews. It was observed in the literature review that there was considerable inconsistency and ambiguity in methods used to cost digital health implementation strategies. However, labour was consistently reported to be the largest implementation-related cost. This was consistent with the views expressed during our prior qualitative interview study with stakeholders which indicated that staff time tracking was a commonly used approach to cost implementation. As a result, the initial prototype included an activity log and a template to capture labour. Other implementation-related costs reported in the literature included consumables, durable assets, and physical space. A separate template was included in the prototype to capture these costs. 

#### Phase 2 findings
The interview findings demonstrated that costing implementation was hindered by the perceived ill-defined boundaries of what constitutes implementation strategies and inconsistencies in terminology used across the disciplines of implementation science, health economics and digital health. The prototype therefore included a planning template to assist users in identifying implementation costs to allow for appropriate data collection. Appendices were included in the prototype with explanatory reference text for users on what could constitute potential implementation costs to assist them in completing the planning template. The resulting prototype was used as stimulus material in the first round of the e-Delphi.

#### Phase 3 findings
Consensus was reached on the core components and design of the instrument from a panel of twelve experts in implementation science, health economic evaluations and/or digital health. Areas of non-consensus included the user’s level of implementation science knowledge, specificity to digital health and accessibility via digital formats.

#### Phase 4 findings
Cost-IS was found to be a flexible instrument that can be tailored to meet the requirements of a range of implementation projects. The Cost-IS instrument enabled comparisons of cost estimates of implementation strategies between three real-world implementation case studies. Labour was the majority of implementation costs. Implementation cost findings provided value for reporting or evaluating, should be customised to project context, and include contextual and analysis information. Adaptions to Cost-IS during the costing process included improved data capture granularity, meaningful categorisation, and enhanced flexibility for analysis.

## Development papers
Read more about the development of Cost-IS in the following papers

[Phase 1](https://doi.org/10.1186%2Fs13012-023-01261-8)

[Phase 2](https://www.researchsquare.com/article/rs-3828958/v1) Preprint

[Phase 3](https://www.researchsquare.com/article/rs-4229774/v1) Preprint

Phase 4 COMING SOON

## Future development

Cost-IS requires further validation including applying Cost-IS from the beginning of new projects to guide prospective collection of implementation costs. Prospective data collection may allow more comprehensive and accurate data to be collected throughout the project and may reduce the reliance on informed assumptions and recall. 

Investigation into incorporating contextual information with implementation cost estimates will improve Cost-IS and was a suggestion from Phase 4. The inclusion of contextual information will improve transparency of implementation cost estimates.

# Contact information

Feel free to reach out via [email](mailto:thomasina.donovan@hdr.qut.edu.au)


*Please cite the relevant journal article when referring to Cost-IS. We recommend this [article](https://www.researchsquare.com/article/rs-4229774/v1).*

*This work is openly licensed via [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)*