---
title: "Worked example"
format: html
---

# Worked example of Cost-IS
## Template 1

The worked example of template 1 includes four implementation strategies with associated activities and resources.


## Template 2A: Data collection- labour

In the worked example of template 2A, all activities associated with the hypothetical implementation were recorded. Each activity instance was given a specific index number because an activity occurred more than once. Similarly, a purpose was recorded for each activity to distinguish it from other similar activities. The implementation strategy related to the respective activity was documented in the same row. Personnel involved in the activity are documented. Each personnel type/role was recorded on a separate row, roles were distinguished by wage rate or title classification. For each activity, the number of personnel for each role was recorded. Finally, the time spent on the activity for that role was documented. The two final columns automatically calculate labour costs when the other columns are completed. The entries columns ‘Activity’, ‘Strategy’ and ‘Role’ are restricted by drop down menus containing what was listed in template 1. Template 1 can be completed iteratively as required by the project.


## Template 2B: Data collection- non-labour

The worked example of template 2B  contains two non-labour resources used in the hypothetical implementation. Each resource is listed in the first column as listed in template 1, with its corresponding strategy in the next column.

## Summary tables

The worked example demonstrates how implementation costs can be summarised by role and implementation strategy.

## Download

[Cost-IS templates- worked example](https://github.com/Thomasina-Donovan/implementation-costing-instrument/raw/main/assets/Cost-IS_WorkedExample_V3.xlsx)
